
SELECT IF(GRADES.grade >= 8, STUDENTS.name, NULL), GRADES.grade, STUDENTs.marks
FROM STUDENTS
    INNER JOIN GRADES
    ON STUDENTS.marks BETWEEN GRADES.min_mark AND GRADES.max_mark

ORDER BY GRADES.grade DESC, STUDENTS.name